### ISSUE TITLE
Add package for direnv

### ISSUE THREAD

**Issue by sunshowers** [oxidecomputer/garbage-compactor#17]
We have some nice integration for direnv in omicron, which lets us cd into it and get a bunch of environment variables immediately. It would be cool to have a package for this.

As of this writing, there's no package available in omniosorg/omnios-extra: https://github.com/search?q=repo%3Aomniosorg%2Fomnios-extra+direnv&type=code.

This is a golang package, available at https://github.com/direnv/direnv.

**Comment by citrus-it** [comment]
Added to helios-omnios-extra in https://github.com/oxidecomputer/helios-omnios-extra/pull/6
